version: '3.8'

services:
  # Backend API Servisi
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_yuYd1DPLWAN7@ep-bold-butterfly-al7aw7ed-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  # Redis (Caching & Message Broker için)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

# Veri kalıcılığı için volume tanımları (İhtiyaç durumunda)
volumes:
  postgres_data:
